version: "2"         
plugins:
  pep8:
    enabled: true

    checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 300
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 30
  nested-control-flow:
    config:
      threshold: 10
  return-statements:
    config:
      threshold: 10
  similar-code:
    config:
      threshold: 20
  identical-code:
    config:
      threshold: 20

exclude_patterns:
- "config.py"
- "tests/"
- "venv/"
